version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - PORT=3000
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
